### ISSUE TITLE
Is eject really necessary?

### ISSUE THREAD

**Issue by lfernando-silva** [johnkmzhou/cordova-create-react-app#1]
Hello, thanks for this amazing tutorial. It was helpful to me.

The only question is about ejection. When I ejected, the config folder was readonly, so I coudn't edit it. But it was not necessary, as the only reason to do that is to change the build path. I could manually move the build to www folder. Alternatively, you can do something as said in [this](https://github.com/facebook/create-react-app/issues/1354) issue, but with caution about support.

**Comment by alex-hall** [comment]
Also wondering this. Definitely don't want to eject if I can help it (from a maintenance standpoint). 

Tried creating a symlink to www locally and create-react-app didn't seem to care

```sh

rm -f build && ln -s www build && yarn build

```

**Comment by alex-hall** [comment]
Might need to go the copy route. I think yarn build blows away the build directory every time (which would blow away all cordova specific stuff)..
